export enum CharCreationError {
  minNameLength = 'MIN_NAME_LENGTH_ERROR',
  maxNameLength = 'MAX_NAME_LENGTH_ERROR',
  minLevel = 'MIN_LEVEL_ERROR',
  maxLevel = 'MAX_LEVEL_ERROR',
  isIntegerLevel = 'INTEGER_LEVEL_ERROR',
  minHealth = 'MIN_HEALTH_ERROR',
  maxHealth = 'MAX_HEALTH_ERROR',
  isIntegerHealth = 'INTEGER_HEALTH_ERROR',
  minAttack = 'MIN_ATTACK_ERROR',
  maxAttack = 'MAX_ATTACK_ERROR',
  isIntegerAttack = 'INTEGER_ATTACK_ERROR',
  minDefence = 'MIN_DEFENCE_ERROR',
  maxDefence = 'MAX_DEFENCE_ERROR',
  isIntegerDefence = 'INTEGER_DEFENCE_ERROR',
  minStrength = 'MIN_STRENGTH_ERROR',
  maxStrength = 'MAX_STRENGTH_ERROR',
  isIntegerStrength = 'INTEGER_STRENGTH_ERROR',
  minDexterity = 'MIN_DEXTERITY_ERROR',
  maxDexterity = 'MAX_DEXTERITY_ERROR',
  isIntegerDexterity = 'INTEGER_DEXTERITY_ERROR',
  minInteligence = 'MIN_INTELIGENCE_ERROR',
  maxInteligence= 'MAX_INTELIGENCE_ERROR',
  isIntegerInteligence = 'INTEGER_INTELIGENCE_ERROR',
  minJink = 'MIN_JINK_ERROR',
  maxJink = 'MAX_JINK_ERROR',
  isIntegerJink = 'INTEGER_JINK_ERROR'
}